- platform: template
  sensors:
    vtr300_tilluft_rf:
      value_template: '{{((states.sensor.vtr300_tilluftsvifte.state | int) * 3) | round(0) }}'
      friendly_name: "Tilluftsmengde"
      unit_of_measurement: 'm³/t'
- platform: template
  sensors:
    vtr300_avtrekk_rf:
      value_template: '{{((states.sensor.vtr300_avtrekksvifte.state | int) * 3) | round(0) }}'
      friendly_name: "Avtrekksmengde"
      unit_of_measurement: 'm³/t'
- platform: template
  sensors:
    vtr300_gjenvinningsgrad:
      value_template: '{{((((states.sensor.vtr300_tillufts_temperatur.state | float ) - (states.sensor.vtr300_inntaks_temperatur.state | float)) / ((states.sensor.vtr300_avtrekks_temperatur.state | float ) - (states.sensor.vtr300_inntaks_temperatur.state | float))) * 100) | round(1) }}'
      unit_of_measurement: '%'
      friendly_name: "Gjenvinningsgrad"

    vtr300_tid_til_filterbytte_months:
      friendly_name: 'Neste filter bytte'
      value_template: >- 
        {% if states('sensor.vtr300_tid_til_filter_bytte_s')|int > 1 %}
          {% set time = states('sensor.vtr300_tid_til_filter_bytte_s') | int %}
          {% set days = (time / 86400) | int %}
          {% set months = (days / 30) | int %}
          {%- if days > 548 -%}
            Mer en 1.5 år
            {%- else -%}
             {%- if days > 31 -%}
              {{ months }} Mnd
            {%- endif -%}           
            {%- if days < 30 -%}
              {{ days }}d
            {%- endif -%}
          {%- endif -%}    
        {% else %}
          Bytt Filter!
        {% endif %} 

#    vtr300_tid_til_filterbytte:
#      friendly_name: 'Neste filter bytte'
#      value_template: >- 
#        {% if states('sensor.vtr300_tid_til_filter_bytte_s')|int > 1 %}
#          {% set time = states('sensor.vtr300_tid_til_filter_bytte_s') | int %}
#          {% set minutes = ((time % 3600) / 60) | int %}
#          {% set hours = ((time % 86400) / 3600) | int %}
#          {% set days = (time / 86400) | int %}
#          {%- if days > 548 -%}
#            Mer en 1.5 år
#            {%- else -%}
#            {%- if days > 0 -%}
#              {{ days }}d
#            {%- endif -%}
#            {%- if hours > 0 -%}
#              {%- if days > 0 -%}
#                {{ ' ' }}
#              {%- endif -%}
#              {{ hours }}t
#            {%- endif -%}
#            {%- if minutes > 0 -%}
#              {%- if days > 0 or hours > 0 -%}
#                {{ ' ' }}
#              {%- endif -%}
#              {{ minutes }}m
#            {%- endif -%}
#          {%- endif -%}    
#        {% else %}
#          Bytt Filter!
#        {% endif %}     

    vtr300_borte_nedtelling_tid_t:
      friendly_name: 'Gjenstående tid når aktiv'
      value_template: >- 
        {% if states('sensor.vtr300_modus_status_register')|int == 5 %}
          {% set time = states('sensor.vtr300_nedtelling_modus_tid_s') | int %}
          {% set minutes = ((time % 3600) / 60) | int %}
          {% set hours = ((time % 86400) / 3600) | int %}

          {%- if time < 60 -%}
            Mindre en 1 minutt
            {%- else -%}
            {%- if hours > 0 -%}
                {{ hours }}t
              {%- endif -%}
            {%- if minutes > 0 -%}
              {%- if hours > 0 -%}
                {{ ' ' }}
              {%- endif -%}
              {{ minutes }}m
            {%- endif -%}
          {%- endif -%}
        {% else %}
          Inaktiv
        {% endif %}             

    vtr300_sommer_vinterd_driftstatus:
      friendly_name: "Aktiv sesong"
      value_template: >-
        {% if states('sensor.vtr300_sommerdrift_vinterdrift')|int == 0 %}
          Sommerdrift
        {% elif states('sensor.vtr300_sommerdrift_vinterdrift')|int == 1 %}
          Vinterdrift
        {% else %}
            Stein dau
        {% endif %}

    vtr300_reg_mode:
      friendly_name: "Regulering"
      value_template: >-
        {% if states('sensor.vtr300_tilluft_rom_avtrekk_reg')|int == 0 %}
          Tilluftsregulering
        {% elif states('sensor.vtr300_tilluft_rom_avtrekk_reg')|int == 1 %}
          Rom reg.
        {% elif states('sensor.vtr300_tilluft_rom_avtrekk_reg')|int == 2 %}
          Avtrekksregulering
        {% else %}
          Stein dau
        {% endif %}

    vtr300_modus_status:
      friendly_name: "Modus"
      value_template: >-
        {% if states('sensor.vtr300_modus_status_register')|int == 0 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 2 %}
          Auto schedule - Lav
        {% elif states('sensor.vtr300_modus_status_register')|int == 0 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 3 %}
          Auto schedule - Normal           
        {% elif states('sensor.vtr300_modus_status_register')|int == 0 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 4 %}
          Auto schedule - Høy                       
        {% elif states('sensor.vtr300_modus_status_register')|int == 1 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 0 %}
          Manuell STOPP 
        {% elif states('sensor.vtr300_modus_status_register')|int == 1 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 1 %}
          Manuell Shitstorm? 
        {% elif states('sensor.vtr300_modus_status_register')|int == 1 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 2 and is_state('input_boolean.vtr300_ppm_mode_auto_enable_modus_status_dummy', 'off') %}
          Manuell Lav  
        {% elif states('sensor.vtr300_modus_status_register')|int == 1 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 3 and is_state('input_boolean.vtr300_ppm_mode_auto_enable_modus_status_dummy', 'off') %}
          Manuell Normal
        {% elif states('sensor.vtr300_modus_status_register')|int == 1 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 4 and is_state('input_boolean.vtr300_ppm_mode_auto_enable_modus_status_dummy', 'off') %}
          Manuell Høy                     
        {% elif states('sensor.vtr300_modus_status_register')|int == 3  %}
          Boost
        {% elif states('sensor.vtr300_modus_status_register')|int == 2  %}
          Party
        {% elif states('sensor.vtr300_modus_status_register')|int == 4  %}
          Ildsted
        {% elif states('sensor.vtr300_modus_status_register')|int == 5  %}
          Borte
        {% elif states('sensor.vtr300_modus_status_register')|int == 6  %}
          ferie
        {% elif states('sensor.vtr300_modus_status_register')|int == 7 %}
          Cooker
        {% elif states('sensor.vtr300_modus_status_register')|int == 8 %}
          Hood
        {% elif states('sensor.vtr300_modus_status_register')|int == 9 %}
          Støvsuger
        {% elif states('sensor.vtr300_modus_status_register')|int == 10 %}
          CDI1
        {% elif states('sensor.vtr300_modus_status_register')|int == 11 %}
          CDI2
        {% elif states('sensor.vtr300_modus_status_register')|int == 12 %}
          Komfyravtrekk          
        {% elif states('sensor.vtr300_modus_status_register')|int == 1 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 2 and is_state('input_boolean.vtr300_ppm_mode_auto_enable_modus_status_dummy', 'on') %}
          PPM Auto - Lav  
        {% elif states('sensor.vtr300_modus_status_register')|int == 1 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 3 and is_state('input_boolean.vtr300_ppm_mode_auto_enable_modus_status_dummy', 'on') %}
          PPM Auto - Normal
        {% elif states('sensor.vtr300_modus_status_register')|int == 1 and states('sensor.vtr300_manuell_modus_kommando_register')|int == 4 and is_state('input_boolean.vtr300_ppm_mode_auto_enable_modus_status_dummy', 'on') %}
          PPM Auto - Høy   
        {% elif states('sensor.vtr300_modus_status_register')|int == 3 and is_state('input_boolean.vtr300_ppm_mode_auto_enable_modus_status_dummy', 'on') %}
          PPM Auto - BOOST            
        {% else %}
          WTF
        {% endif %}    

    vtr300_manuell_button_modus_status:
      friendly_name: "Manuell button modus status"
      value_template: >-
        {% if states('sensor.vtr300_modus_status_register')|int == 0 and states('sensor.vtr300_manuell_modus_kommando_register')|int > 0 %}
          Auto schedule
        {% elif states('sensor.vtr300_modus_status_register')|int == 1 and states('sensor.vtr300_manuell_modus_kommando_register')|int > 0 and is_state('input_boolean.vtr300_ppm_mode_auto_enable_modus_status_dummy', 'off') %}
          Manuell
        {% elif states('sensor.vtr300_modus_status_register')|int == 1 and states('sensor.vtr300_manuell_modus_kommando_register')|int > 0 and is_state('input_boolean.vtr300_ppm_mode_auto_enable_modus_status_dummy', 'on') %}
          PPM Auto         
        {% elif states('sensor.vtr300_modus_status_register')|int > 0 and states('sensor.vtr300_manuell_modus_kommando_register')|int > 0 and is_state('input_boolean.vtr300_ppm_mode_auto_enable_modus_status_dummy', 'off') %}
          Standby            
        {% else %}
          Av
        {% endif %}     

